# docker-compose.yml
version: '2.1'
services:
        #  filebeat:
        #    image: elastic/filebeat:7.7.0
#    command: filebeat -e -strict.perms=false
#    restart: always
#    volumes:
#      - /home/tom/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
#      - /home/tom/data:/usr/share/filebeat/data
        #   links:
        #     - kibana
        #      - elasticsearch
        #    hostname: filebeat

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://localhost:9200"
    depends_on:
      - elasticsearch
    hostname: kibana

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - "discovery.type=single-node"
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: logstash:7.7.0
    hostname: logstash
    volumes:
     - ./logstash/comm:/usr/share/logstash/comm:ro
     - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    ports:
     - "5000:5000"

